language: node_js

node_js:
  - 0.10
  - 0.12
  - 4
  - 6
  - 8
  - node

cache:
  directories:
    - node_modules

script:
  - node ./bin/cake build:except-parser
  - node ./bin/cake build:parser
  - node --harmony ./bin/cake build:full
  - node ./bin/cake build:browser
  - node --harmony ./bin/cake test
  - node --harmony ./bin/cake test:browser
