environment:
  matrix:
    - nodejs_version: '0.8'
    - nodejs_version: '0.10'
    - nodejs_version: '0.12'
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'
    - nodejs_version: '' # Installs latest.

install:
  - ps: Install-Product node $env:nodejs_version
  - IF NOT [%nodejs_version%] == [] IF "%nodejs_version%" LSS 4 npm install --global npm@2
  - node --version
  - npm --version
  - npm install

cache:
  - node_modules

test_script:
  - node ./bin/cake build:except-parser
  - node ./bin/cake build:parser
  - node --harmony ./bin/cake build:full
  - node ./bin/cake build:browser
  - node --harmony ./bin/cake test
  - node --harmony ./bin/cake test:browser

build: off

version: "{build}"
